import { render, screen, fireEvent, waitFor, cleanup } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { describe, it, vi, expect, afterEach } from 'vitest';
import { AdminEmailCampaignsPage } from '@/pages/AdminEmailCampaignsPage';
import { AdminEmailCampaignEditorPage } from '@/pages/AdminEmailCampaignEditorPage';
import { api } from '@/services/api';
vi.mock('@/services/api', ()=>({ api:{
  listEmailCampaigns: vi.fn(async()=>[{id:'1',name:'C',template_id:'t1',audience_type:'all_users',status:'draft',updated_at:'now',created_at:'now'}]),
  listEmailTemplates: vi.fn(async()=>[{id:'t1',name:'T'}]),
  createEmailCampaign: vi.fn(async(p)=>({id:'2',...p,updated_at:'',created_at:''})),
  getEmailCampaign: vi.fn(async()=>({id:'1',name:'C',template_id:'t1',audience_type:'all_users',status:'draft',variables_json:{},updated_at:'',created_at:''})),
  patchEmailCampaign: vi.fn(), archiveEmailCampaign: vi.fn(), previewEmailCampaign: vi.fn(async()=>({subject:'s',preheader:'p',html_body:'h',text_body:'t',missing_variables:[]})), previewCampaignRecipients: vi.fn(async()=>({total_candidates:10,sendable_count:7,suppressed_count:1,invalid_count:1,duplicate_count:1,sample_recipients:['a@b.com'],suppressed_samples:['s@b.com'],invalid_samples:['bad']})), sendCampaign: vi.fn(async()=>({total_candidates:10,sendable_count:7,sent_count:0,failed_count:0,skipped_count:3})), getCampaignSendStatus: vi.fn(async()=>({campaign_id:'1',status:'sending',total:7,queued:7,sent:0,delivered:0,bounced:0,complained:0,failed:0,skipped:0,completion_percentage:0})), testSendCampaign: vi.fn(async()=>({status:'sent'}))
}, getErrorDetail: ()=> 'err'}));

afterEach(() => cleanup());

describe('campaign pages',()=>{
  it('list renders', async()=>{render(<MemoryRouter><AdminEmailCampaignsPage/></MemoryRouter>); expect(await screen.findByText('C')).toBeInTheDocument();});
  it('editor preview and test send', async()=>{render(<MemoryRouter initialEntries={['/admin/settings/email/campaigns/1']}><Routes><Route path='/admin/settings/email/campaigns/:campaignId' element={<AdminEmailCampaignEditorPage/>}/></Routes></MemoryRouter>); await waitFor(()=>screen.getByText('Edit Email Campaign')); fireEvent.click(screen.getByText('Preview')); fireEvent.click(screen.getByText('Preview recipients')); fireEvent.change(screen.getByLabelText('to email'),{target:{value:'a@b.com'}}); fireEvent.click(screen.getByText('Send test')); expect(await screen.findByText(/total candidates 10/)).toBeInTheDocument();});
  it('send button disabled until confirmation matches', async()=>{render(<MemoryRouter initialEntries={['/admin/settings/email/campaigns/1']}><Routes><Route path='/admin/settings/email/campaigns/:campaignId' element={<AdminEmailCampaignEditorPage/>}/></Routes></MemoryRouter>); const btn=await screen.findByRole('button',{name:'Send campaign'}); expect(btn).toBeDisabled(); fireEvent.change(screen.getByLabelText('campaign confirmation'), {target:{value:'SEND CAMPAIGN'}}); expect(btn).toBeDisabled();});
  it('send queues and displays sending progress, disabling repeat send', async()=>{render(<MemoryRouter initialEntries={['/admin/settings/email/campaigns/1']}><Routes><Route path='/admin/settings/email/campaigns/:campaignId' element={<AdminEmailCampaignEditorPage/>}/></Routes></MemoryRouter>); fireEvent.change(await screen.findByLabelText('campaign confirmation'), {target:{value:'SEND CAMPAIGN'}}); fireEvent.change(screen.getByDisplayValue('draft'), {target:{value:'ready'}}); fireEvent.click(screen.getByText('Preview recipients')); const btn=screen.getByRole('button',{name:'Send campaign'}); fireEvent.click(btn); expect(await screen.findByText('campaign status sending')).toBeInTheDocument(); expect(screen.getByText('total recipients 7')).toBeInTheDocument(); expect(screen.getByText('completion 0%')).toBeInTheDocument(); expect(screen.getByRole('button',{name:'Send campaign'})).toBeDisabled();});
  it('failed status renders safely', async()=>{vi.mocked(api.getCampaignSendStatus).mockResolvedValueOnce({campaign_id:'1',status:'failed',total:5,queued:0,sent:0,delivered:0,bounced:0,complained:0,failed:2,skipped:3,completion_percentage:100} as const); render(<MemoryRouter initialEntries={['/admin/settings/email/campaigns/1']}><Routes><Route path='/admin/settings/email/campaigns/:campaignId' element={<AdminEmailCampaignEditorPage/>}/></Routes></MemoryRouter>); fireEvent.change(await screen.findByLabelText('campaign confirmation'), {target:{value:'SEND CAMPAIGN'}}); fireEvent.change(screen.getByDisplayValue('draft'), {target:{value:'ready'}}); fireEvent.click(screen.getByText('Preview recipients')); fireEvent.click(screen.getByRole('button',{name:'Send campaign'})); expect(await screen.findByText('campaign status failed')).toBeInTheDocument(); expect(screen.getByText('failed 2')).toBeInTheDocument();});
});
