import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { api, getErrorDetail } from '@/services/api';
import type { EmailCampaign, EmailCampaignCreate, EmailCampaignPreviewResponse } from '@/types/api';

export function AdminEmailCampaignEditorPage(){
  const {campaignId}=useParams(); const nav=useNavigate();
  const [f,setF]=useState<EmailCampaignCreate>({name:'',template_id:'',audience_type:'all_users',status:'draft',subject_override:'',preheader_override:'',variables_json:{}});
  const [templates,setTemplates]=useState<Array<{id:string;name:string}>>([]); const [preview,setPreview]=useState<EmailCampaignPreviewResponse | null>(null); const [toEmail,setToEmail]=useState(''); const [provider,setProvider]=useState('default'); const [msg,setMsg]=useState(''); const [err,setErr]=useState('');
  useEffect(()=>{api.listEmailTemplates().then((list)=>setTemplates(list.map(t=>({id:t.id,name:t.name})))); if(campaignId) api.getEmailCampaign(campaignId).then((c: EmailCampaign)=>setF({name:c.name,template_id:c.template_id,audience_type:c.audience_type,audience_filters_json:c.audience_filters_json??null,status:c.status,subject_override:c.subject_override??'',preheader_override:c.preheader_override??'',variables_json:c.variables_json??{}})).catch(e=>setErr(getErrorDetail(e)));},[campaignId]);
  const archived=f.status==='archived';
  return <div><h2>{campaignId?'Edit':'New'} Email Campaign</h2>{err&&<div>{err}</div>}<input value={f.name} disabled={archived} onChange={e=>setF({...f,name:e.target.value})}/><select value={f.template_id} disabled={archived} onChange={e=>setF({...f,template_id:e.target.value})}><option value=''>select template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input value={f.audience_type} disabled={archived} onChange={e=>setF({...f,audience_type:e.target.value})}/><select value={f.status} onChange={e=>setF({...f,status:e.target.value as 'draft'|'ready'|'archived'})}><option>draft</option><option>ready</option><option>archived</option></select><input value={f.subject_override||''} disabled={archived} onChange={e=>setF({...f,subject_override:e.target.value})}/><input value={f.preheader_override||''} disabled={archived} onChange={e=>setF({...f,preheader_override:e.target.value})}/><textarea value={JSON.stringify(f.variables_json||{})} disabled={archived} onChange={e=>setF({...f,variables_json:JSON.parse(e.target.value||'{}') as Record<string, unknown>})}/><button onClick={async()=>{try{if(campaignId){await api.patchEmailCampaign(campaignId,f);} else {const c=await api.createEmailCampaign(f); nav(`/admin/settings/email/campaigns/${c.id}`);}}catch(e){setErr(getErrorDetail(e));}}}>Save</button>{campaignId&&<button onClick={async()=>{await api.archiveEmailCampaign(campaignId); setF({...f,status:'archived'});}}>Archive</button>}<button onClick={async()=>{if(!campaignId) return; setPreview(await api.previewEmailCampaign(campaignId,{variables_json:f.variables_json??{}}));}}>Preview</button>{preview&&<div><div>{preview.subject}</div><div>{preview.preheader}</div><div>{preview.html_body}</div><div>{preview.text_body}</div><div>{preview.missing_variables.join(',')}</div></div>}<h3>Test send</h3><select value={provider} onChange={e=>setProvider(e.target.value)}><option value='default'>default</option><option value='resend'>resend</option><option value='sendgrid'>sendgrid</option></select><input aria-label='to email' value={toEmail} onChange={e=>setToEmail(e.target.value)}/><button onClick={async()=>{if(!campaignId) return; try{await api.testSendCampaign(campaignId,{to_email:toEmail,provider:provider==='default'?undefined:(provider as 'resend'|'sendgrid'),variables_json:f.variables_json??{}}); setMsg('sent');}catch(e){setMsg(getErrorDetail(e));}}}>Send test</button><div>{msg}</div></div>;
}
