import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { http } from '@/services/http';

type Doc = { id: string; title: string; category?: string|null; jurisdiction?: string|null; source_type: string; status: string; indexed_at?: string|null; description?: string|null; original_filename?: string|null; mime_type?: string|null; size_bytes?: number|null; extraction_status: string; extraction_error?: string|null; index_status: string; index_error?: string|null };
type Sub = { id: string; title: string; status: string; suggested_category?: string|null; suggested_jurisdiction?: string|null; reason?: string|null; admin_notes?: string|null; reviewed_at?: string|null; source_document_id?: string|null; source_user_id?: string|null; source_drive_file_id?: string|null; resulting_system_document_id?: string|null };
type Ref = { id: string; url: string; title: string; source_domain?: string|null; jurisdiction?: string|null; court_or_institution?: string|null; legal_area?: string|null; document_type?: string|null; status: string; retrieved_at?: string|null; last_checked_at?: string|null };
type Log = { id: string; actor: string; action: string; target_type: string; target_id: string; created_at: string; metadata_json?: Record<string, unknown>|null };

const tabs = ['Library', 'Upload', 'Review Submissions', 'Web References', 'Audit Log'] as const;

export function AdminSystemIntelligencePage() {
  const qc = useQueryClient();
  const [tab, setTab] = useState<(typeof tabs)[number]>('Library');
  const [titleError, setTitleError] = useState<string | null>(null);
  const [selectedSub, setSelectedSub] = useState<Sub | null>(null);
  const [mode, setMode] = useState<'approve'|'reject'|null>(null);
  const [refStatusFilter, setRefStatusFilter] = useState<'all'|'candidate'|'active'|'archived'|'untrusted'>('all');

  const docs = useQuery<Doc[]>({ queryKey: ['si-docs'], queryFn: async () => (await http.get('/api/v1/admin/system-intelligence/documents')).data });
  const submissions = useQuery<Sub[]>({ queryKey: ['si-subs'], queryFn: async () => (await http.get('/api/v1/admin/system-intelligence/submissions')).data });
  const refs = useQuery<Ref[]>({ queryKey: ['si-refs'], queryFn: async () => (await http.get('/api/v1/admin/system-intelligence/web-references')).data });
  const logs = useQuery<Log[]>({ queryKey: ['si-audit'], queryFn: async () => (await http.get('/api/v1/admin/system-intelligence/audit-log')).data });

  const refresh = () => { qc.invalidateQueries({ queryKey: ['si-docs'] }); qc.invalidateQueries({ queryKey: ['si-subs'] }); qc.invalidateQueries({ queryKey: ['si-refs'] }); qc.invalidateQueries({ queryKey: ['si-audit'] }); };
  const docAction = useMutation({ mutationFn: async ({ id, action }: { id: string; action: 'activate'|'archive'|'reindex'|'delete' }) => action === 'delete' ? (await http.delete(`/api/v1/admin/system-intelligence/documents/${id}`)).data : (await http.post(`/api/v1/admin/system-intelligence/documents/${id}/${action}`)).data, onSuccess: refresh });
  const createDoc = useMutation({ mutationFn: async (payload: FormData) => (await http.post('/api/v1/admin/system-intelligence/documents', payload)).data, onSuccess: refresh });
  const moderateSub = useMutation({ mutationFn: async ({ id, action, payload }: { id: string; action: 'approve'|'reject'; payload: Record<string, unknown> }) => (await http.post(`/api/v1/admin/system-intelligence/submissions/${id}/${action}`, payload)).data, onSuccess: refresh });
  const refAction = useMutation({ mutationFn: async ({ id, action }: { id: string; action: 'approve'|'archive'|'delete' }) => action === 'delete' ? (await http.delete(`/api/v1/admin/system-intelligence/web-references/${id}`)).data : (await http.post(`/api/v1/admin/system-intelligence/web-references/${id}/${action}`)).data, onSuccess: refresh });
  const createRef = useMutation({ mutationFn: async (payload: Record<string, unknown>) => (await http.post('/api/v1/admin/system-intelligence/web-references', payload)).data, onSuccess: refresh });

  return <div className="space-y-4"><h1 className="text-2xl font-semibold">System Intelligence</h1>
    <div className="flex flex-wrap gap-2">{tabs.map((t)=><button key={t} type="button" onClick={()=>setTab(t)} className={`rounded border px-3 py-1 text-sm ${tab===t?'border-blue-500 bg-blue-600 text-white':'border-slate-700 bg-slate-900 text-slate-100'}`}>{t}</button>)}</div>
    {tab==='Library' && <table className='w-full text-sm'><thead><tr><th>Title</th><th>File</th><th>Mime</th><th>Size</th><th>Extract</th><th>Index</th><th>Indexed</th><th>Actions</th></tr></thead><tbody>{(docs.data||[]).map((d)=><tr key={d.id}><td>{d.title}</td><td>{d.original_filename||'-'}</td><td>{d.mime_type||'-'}</td><td>{d.size_bytes??'-'}</td><td>{d.extraction_status}{d.extraction_error?` (${d.extraction_error})`:''}</td><td>{d.index_status}{d.index_error?` (${d.index_error})`:''}</td><td>{d.indexed_at||'-'}</td><td className='space-x-1'>{['activate','archive','reindex','delete'].map((a)=><button key={a} onClick={()=>docAction.mutate({id:d.id,action:a as never})} className='rounded border px-2'>{a}</button>)}</td></tr>)}</tbody></table>}
    {tab==='Upload' && <form onSubmit={(e)=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const title=String(fd.get('title')||'').trim(); if(!title){setTitleError('Title is required'); return;} if(!fd.get('file')){setTitleError('File is required'); return;} setTitleError(null); createDoc.mutate(fd);}} className='space-y-2'>
      <input name='title' placeholder='Title' className='w-full rounded bg-slate-800 p-2'/>{titleError && <div className='text-red-300'>{titleError}</div>}
      <textarea name='description' placeholder='Description' className='w-full rounded bg-slate-800 p-2'/><input name='category' placeholder='Category' className='w-full rounded bg-slate-800 p-2'/><input name='jurisdiction' placeholder='Jurisdiction' className='w-full rounded bg-slate-800 p-2'/><input name='source_type' defaultValue='admin_upload' className='w-full rounded bg-slate-800 p-2'/><input name='file' type='file' accept='.pdf,.txt,.md,.docx' className='w-full rounded bg-slate-800 p-2'/><button className='rounded bg-blue-600 px-3 py-2 text-white'>Upload</button></form>}
    {tab==='Review Submissions' && <div className='space-y-2'>{(submissions.data||[]).map((s)=><div key={s.id} className='rounded border p-2'><div className='font-medium'>{s.title} ({s.status})</div><div className='text-xs'>Source: {s.source_document_id} · Submitter: {s.source_user_id || '-'}</div><div className='text-xs'>Suggested: {s.suggested_category||'-'} / {s.suggested_jurisdiction||'-'}</div><div className='text-xs text-slate-400'>{s.reason||''}</div><div className='text-xs'>Reviewed at: {s.reviewed_at || '-'}</div>{s.resulting_system_document_id && <div className='text-xs'>Resulting document: {s.resulting_system_document_id}</div>}<div className='mt-1 space-x-1'><button className='rounded border px-2' onClick={()=>{setSelectedSub(s);setMode('approve');}}>Approve</button><button className='rounded border px-2' onClick={()=>{setSelectedSub(s);setMode('reject');}}>Reject</button></div></div>)}
      {selectedSub && mode === 'approve' && <form className='rounded border p-3 space-y-2' onSubmit={(e)=>{e.preventDefault();const fd=new FormData(e.currentTarget);moderateSub.mutate({id:selectedSub.id,action:'approve',payload:{title:String(fd.get('title')||selectedSub.title),category:String(fd.get('category')||''),jurisdiction:String(fd.get('jurisdiction')||''),admin_notes:String(fd.get('admin_notes')||''),is_active:fd.get('is_active')==='on'}},{onError:(err)=>alert(((err as {response?:{data?:{detail?:string}}})?.response?.data?.detail)||'Approval failed: source content inaccessible or empty')});setSelectedSub(null);setMode(null);}}><h3>Approve submission</h3><input name='title' defaultValue={selectedSub.title} className='w-full rounded bg-slate-800 p-2'/><input name='category' defaultValue={selectedSub.suggested_category||''} className='w-full rounded bg-slate-800 p-2'/><input name='jurisdiction' defaultValue={selectedSub.suggested_jurisdiction||''} className='w-full rounded bg-slate-800 p-2'/><textarea name='admin_notes' className='w-full rounded bg-slate-800 p-2' placeholder='admin notes'/><label className='text-sm'><input type='checkbox' name='is_active' defaultChecked/> Activate immediately</label><div className='space-x-2'><button className='rounded border px-2'>Submit</button><button type='button' className='rounded border px-2' onClick={()=>{setSelectedSub(null);setMode(null);}}>Cancel</button></div></form>}
      {selectedSub && mode === 'reject' && <form className='rounded border p-3 space-y-2' onSubmit={(e)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const admin_notes=String(fd.get('admin_notes')||'').trim(); if(!admin_notes){alert('admin_notes required'); return;} moderateSub.mutate({id:selectedSub.id,action:'reject',payload:{admin_notes}}); setSelectedSub(null); setMode(null);}}><h3>Reject submission</h3><textarea name='admin_notes' required className='w-full rounded bg-slate-800 p-2' placeholder='Reason for rejection'/><div className='space-x-2'><button className='rounded border px-2'>Reject</button><button type='button' className='rounded border px-2' onClick={()=>{setSelectedSub(null);setMode(null);}}>Cancel</button></div></form>}
      </div>}
    {tab==='Web References' && <div className='space-y-3'>
      <label className='text-sm'>Status filter <select value={refStatusFilter} onChange={(e)=>setRefStatusFilter(e.target.value as never)} className='ml-2 rounded bg-slate-800 p-1'><option value='all'>all</option><option value='candidate'>candidate</option><option value='active'>active</option><option value='archived'>archived</option><option value='untrusted'>untrusted</option></select></label>
      <table className='w-full text-sm'><thead><tr><th>Title</th><th>URL</th><th>Domain</th><th>Jurisdiction</th><th>Court/Institution</th><th>Doc Type</th><th>Legal Area</th><th>Status</th><th>Retrieved</th><th>Last Checked</th><th>Actions</th></tr></thead><tbody>{(refs.data||[]).filter((r)=>refStatusFilter==='all' || r.status===refStatusFilter).map((r)=><tr key={r.id}><td>{r.title}</td><td>{r.url}</td><td>{r.source_domain||'-'}</td><td>{r.jurisdiction||'-'}</td><td>{r.court_or_institution||'-'}</td><td>{r.document_type||'-'}</td><td>{r.legal_area||'-'}</td><td>{r.status}</td><td>{r.retrieved_at||'-'}</td><td>{r.last_checked_at||'-'}</td><td className='space-x-1'><button className='rounded border px-2' onClick={()=>refAction.mutate({id:r.id,action:'approve'})}>approve/activate</button><button className='rounded border px-2' onClick={()=>refAction.mutate({id:r.id,action:'archive'})}>archive</button><button className='rounded border px-2' onClick={()=>refAction.mutate({id:r.id,action:'delete'})}>delete</button></td></tr>)}</tbody></table>
      <form onSubmit={(e)=>{e.preventDefault(); const fd=new FormData(e.currentTarget); createRef.mutate({url:String(fd.get('url')||''),title:String(fd.get('title')||''),source_domain:String(fd.get('source_domain')||''),jurisdiction:String(fd.get('jurisdiction')||''),court_or_institution:String(fd.get('court_or_institution')||''),legal_area:String(fd.get('legal_area')||''),document_type:String(fd.get('document_type')||'')}); e.currentTarget.reset();}} className='grid grid-cols-2 gap-2'><input name='url' placeholder='URL' className='rounded bg-slate-800 p-2'/><input name='title' placeholder='Title' className='rounded bg-slate-800 p-2'/><input name='source_domain' placeholder='source_domain' className='rounded bg-slate-800 p-2'/><input name='jurisdiction' placeholder='jurisdiction' className='rounded bg-slate-800 p-2'/><input name='court_or_institution' placeholder='court_or_institution' className='rounded bg-slate-800 p-2'/><input name='legal_area' placeholder='legal_area' className='rounded bg-slate-800 p-2'/><input name='document_type' placeholder='document_type' className='rounded bg-slate-800 p-2'/><button className='rounded bg-blue-600 px-3 py-2 text-white'>Add candidate</button></form></div>}
    {tab==='Audit Log' && <table className='w-full text-sm'><thead><tr><th>Actor</th><th>Action</th><th>Target</th><th>Timestamp</th><th>Metadata</th></tr></thead><tbody>{(logs.data||[]).map((l)=><tr key={l.id}><td>{l.actor}</td><td>{l.action}</td><td>{l.target_type}:{l.target_id}</td><td>{l.created_at}</td><td>{JSON.stringify(l.metadata_json||{})}</td></tr>)}</tbody></table>}
  </div>;
}
